### PR TITLE
feat(content): use content from emdaer/emdaer as site sections

### PR DESCRIPTION
**Pull request by infiniteluke**
**What**:
Add a couple site sections shared from https://github.com/emdaer/emdaer

**Why**:
Updates to the emdaer readme should reflect in the website 

**How**:
remark, remark-react

**Checklist**:

- [X] Documentation
- [X] Tests N/A
- [X] Ready to be merged 
- [X] Added myself to AUTHORS

### CODE REVIEW

**Comment by infiniteluke** [comment]
☝️ I have _no_ idea what we should do to make this look presentable.

**Comment by infiniteluke** [comment]
Design notes from @amazingrando

>Notebook + other emojis to add color
Link to GitHub under “Create and Maintain..”
Bring in other colors as headers maybe
Try making first jumbotron colorful at top
Scale down h3 1.45 maybe dark gray
“Using emdaer in your project”
Add icons for each section - the noun project
Footer - simple/short

**Comment by flipactual** [comment]
@infiniteluke per https://github.com/emdaer/emdaer.github.io/pull/12#issuecomment-345818828 – sorry, no

We're going to continue mimicking Facebook's open source projects' websites' designs as closely as we're able

Design is not an area where emdaer cares to innovate

**Comment by infiniteluke** [comment]
@flipactual Noted. Looking at https://reactjs.org/, it includes a couple of the suggestions @amazingrando made. So, I'll consider those on mark. Beyond that, I'll take the rest of my cues for https://reactjs.org/.

**Comment by infiniteluke** [comment]
per discussion prepack.io and https://facebook.github.io/jest/ are better examples. We'll keep the website _super_ simple since emdaer is not a big project.

**Comment by infiniteluke** [comment]
Going to merge this and take care of design changes in a separate branch

**Pull request merged**
